Small Additions
AkaruiDevelopment/aoi.js pull request #468
Opened 2023-07-18 01:46 UTC by Faf4a

- made `errorMessage` support parser
- updated `$findObjectProperty[property;format?]` to work with all object functions
- did the same with `$removeObjectProperty[...properties]`
- added `$updateObjectProperty[property;newproperty]`

2023-07-18 18:48 UTC, Faf4a commented
## Added
- `$getObjectValues[object]`
- `$getObjectKeys[object]`
- `$objectExists[object]`
- `$deleteObject[object]`
- `$cloneObject[object;cloned object name]`

## Changes
- `$createObject[objectname;json]`
 - Ability to create multiple objects.
- `$getObjectProperty[objectname;property]`
- Renamed `$addObjectProperty` to `$setObjectProperty` and changed usage to `[objectname, propertyname, propertyvalue]`
- All object functions now work "together", as well you're now able to create multiple objects.

2023-07-18 19:16 UTC, Faf4a commented
Fixed `$addTimestamp` to actually be able to add timestamps, for example: `$addTimestamp[1;1689706824079ms]` or `$addTimestamp[1689706824079ms]`.

2023-07-19 00:18 UTC, Faf4a commented
Made `$getLeaderboardInfo` support only `aoi.db` for now as it's the main database + dbdjs.db is unstable, aoimongo died ages ago no idea about the other one.

2023-07-24 02:22 UTC, USERSATOSHI approved these changes
LGTM

2023-07-24 02:33 UTC, Leref requested changes

2023-07-24 02:33 UTC, Leref commented on src/core/interpreter.js
Revert this as interpreter will change.

2023-07-24 02:40 UTC, merged