fixes
AkaruiDevelopment/aoi.js pull request #503
Opened 2023-11-27 20:13 UTC by Faf4a

Fixes:
$fetchClientValues, $bulk

Additions:
$awaitExecute[awaited], $resolveStickerID[resolver], $sendSticker[resolver]

Others:
Move custombox component to AoiError class.

Closes #497 
Closes #498 
Closes #502 
Closes #504

2023-11-30 17:41 UTC, Leref commented on src/handler/AoiStart.js
> +    if (client.aoiOptions.aoiWarning !== false && client.aoiOptions.aoiAutoUpdate === false) {
This isn't true, since aoiAutoUpdate is always false, it has it's own thing.

2023-11-30 17:42 UTC, Leref commented on src/classes/Database.js
> +            // console.log(`[@akarui/aoi.db] Connected ${type} database`);
We should use customBox logging

2023-11-30 17:42 UTC, Leref requested changes
some things

2023-11-30 20:40 UTC, Faf4a commented on src/classes/Database.js
> +            // console.log(`[@akarui/aoi.db] Connected ${type} database`);
Resolved.

2023-11-30 20:42 UTC, Faf4a commented on src/handler/AoiStart.js
> +    if (client.aoiOptions.aoiWarning !== false && client.aoiOptions.aoiAutoUpdate === false) {
Reverted.

2023-12-01 14:17 UTC, Leref approved these changes

2023-12-01 14:17 UTC, merged